---
name: Test

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/dependabot.yml'

env:
  IMAGE: ghcr.io/redlinetriad/molecule-vagrant-qemu-action

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Build Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Molecule default pipeline
        env:
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          docker run \
          -v $(pwd)/test_files/:/var/test_files \
          ${{ env.IMAGE }}:test \
          sh -c "\
            molecule --version \
            && molecule init role --driver-name vagrant redlinetriad.validate \
            && cd validate \
            && cp /var/test_files/molecule.yml molecule/default/molecule.yml \
            && sed -i 's/redlinetriad.//g' molecule/default/converge.yml \
            && molecule test \
          "
